[functions]
  included_files = ["node_modules/sharp/**/*", "netlify/functions/layouts/**", "site/meta.json"]

[build]
  base    = ""
  publish = "build"
  command = "curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.38.2 && /opt/buildhome/.deno/bin/deno task netlify:build"
