[build]
  base    = ""
  publish = "build"
  command = "curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.14.3 && /opt/buildhome/.deno/bin/deno run --unstable --no-check --import-map=import_map.json -A ./src/build.ts"
