[build]
  base    = ""
  publish = "build"
  command = "curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.24.2 && /opt/buildhome/.deno/bin/deno run --unstable --no-check -A ./gustwind/build.ts"
