enum STATES {
  IDLE,
  PARSE_EXPRESSION,
  PARSE_NAMED_LINK_URL,
  PARSE_NAMED_LINK_CONTENT,
  PARSE_MONOSPACE,
  PARSE_BOLD,
  PARSE_ITALIC,
  PARSE_SIMPLE_LINK,
  PARSE_BLOCK_START,
  PARSE_BLOCK_CONTENT,
  PARSE_BLOCK_END,
}

export { STATES };
